### ISSUE TITLE
Migrate to our new elastic instance (elastic.surfpol.nl)

### ISSUE THREAD

**Issue by jelmerderonde** [SURFpol/pol-harvester#92]
- [x] Prevent server start fails, because ES is down
- [ ] Create one or more accounts with minimal required priveleges for our different apps.
- [x] Migrate indices (https://www.elastic.co/guide/en/elasticsearch/reference/current/reindex-upgrade-remote.html)
- [x] Change urls in projects

**Comment by fako** [comment]
I repeatedly got Elastic Search timeout that lasted longer than 30s. They ended in 504's so definitely server timeouts. Then I clicked around in Kibana and suddenly Elastic Search would connect normally. Should I wake up the Elastic Search somehow?? @jelmerderonde

**Comment by fako** [comment]
Yep, this is turning into a single point of failure. If the ES instance is down all containers refuse to start. I'm adding a todo which changes that. When ES fails only ES code should raise runtime errors

**Comment by jelmerderonde** [comment]
I think Elastic is stable now and I'v made a dump of all the indices (that were still intact, there has been some data corruption) on the old servers

@fako is it ok to tell Matthijs to take down the old servers?

**Comment by fako** [comment]
We're not fixing the "read-only" accounts for now, because during the tests we'll open Elastic to the world and we'll leave it closed for the rest of the time. Problem with having read-only accounts and an open ES is that scanners will start probing the password of the "elastic" user. This is a hard password to brute force, but we want to be careful anyway. One possible solution would be to put ES behind an APIGateway (or similar) and throttle logins or we move the query code into a backend, which the frontend can then safely use. That last option has some preference, because that's how it works for the current search portal.
